services:
  Devouted\AsCachedAttribute\Listener\CacheResponseListener:
    arguments: [ '@cache.app' ]
    tags:
      - { name: kernel.event_listener, event: kernel.controller_arguments }
      - { name: kernel.event_listener, event: kernel.response }
